### PR TITLE
fix: EVM compiler error in hardhat plugins

### PR DESCRIPTION
**Pull request by kfichter**
Fixes a bug where EVM errors wouldn't be propagated because another error would happen before the EVM errors could be returned. Whoops!

### CODE REVIEW

**Review by karlfloersch — APPROVED** [review]
Lacking some context but the general form of this fix looks like it could easily cause issues.

🚢!

**Review by ben-chain — APPROVED** [review]
👍 LGTM!

**Comment by kfichter** [comment]
For additional context, https://github.com/ethereum-optimism/plugins/blob/6d8ff0cee0dd950536f98d8df32b1657c7accf39/src/hardhat/compiler/index.ts#L154 was causing issues when the user had errors in their evm code but not in their ovm code. The line would start iterating through `ovmOutput.contracts` not realizing that `evmOutput.contracts` was undefined, which resulted in an error like: `TypeError: Cannot use 'in' operator to search for '@openzeppelin/contracts/math/SafeMath.sol' in undefined`.

**Comment by kfichter** [comment]
Replacing `filename in evmOutput.contracts` with `filename in Object.keys(evmOutput.contracts || {})` ensures that we'll never get this particular error.

**Pull request merged**
